import Modal from '@/components/Modal'
import './globals.css'

export const metadata = {
  title: 'Trello 2.O Clone',
  description: 'Generated by Varad Patil',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F8]'>
        {children}
        <Modal/>
        </body>
    </html>
  )
}
